### ISSUE TITLE
Fix Dashboard route

### ISSUE THREAD

**Issue by BuddyLongLegs** [opencodeiiita/SaveMyForm-Backend#98]
Fix the dashboard route in `user.controller.js`. This is following error that is popping:

```
TypeError: user.populate(...).aggregate is not a function
    at dashboard (file:///home/runner/SaveMyForm-Backend-Dev/controllers/user.controller.js:121:8)
    at Layer.handle [as handle_request] (/home/runner/SaveMyForm-Backend-Dev/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/SaveMyForm-Backend-Dev/node_modules/express/lib/router/route.js:144:13)
    at authMiddleware (file:///home/runner/SaveMyForm-Backend-Dev/middlewares/verify.middleware.js:42:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by GammaMicrowave** [comment]
claim

**Comment by BuddyLongLegs** [comment]
Assigned to @GammaMicrowave
